import { 
  BroadcastChecklistRow, 
  IncidentTicket, 
  Employee, 
  OvertimeLog, 
  TimeOffDeduction, 
  GoogleAccessPolicy,
  ControlTecnicoRow,
  Ipv4Network,
  IpAssignment
} from './types';

export const DEFAULT_ACCESS_POLICY: GoogleAccessPolicy = {
  mode: 'authorized_only', // Modo restringido: solo correos autorizados por los administradores
  authorizedEmails: [
    'fmallam@unemi.edu.ec',
    'fmalla@comunica.ec',
    'dquevedo@comunica.ec',
    'multimediaectvq@gmail.com',
  ],
  adminEmails: [
    'fmallam@unemi.edu.ec',
    'fmalla@comunica.ec',
  ],
};

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    nombre: 'Darwin Quevedo',
    cargo: 'Analista de Sistemas y Multimedia Broadcasting 2',
    tecnicoCode: 'DQuevedo',
    email: 'dquevedo@comunica.ec',
    saldoHoras: 0,
    codigoSeguridad: 'DQ-2026',
    area: 'multimedia',
  },
  {
    id: 'emp-2',
    nombre: 'Freddy Malla',
    cargo: 'Analista de Sistemas y Multimedia Broadcasting 2',
    tecnicoCode: 'Fmalla',
    email: 'fmalla@comunica.ec',
    saldoHoras: 0,
    codigoSeguridad: 'FM-2026',
    area: 'multimedia',
  },
  {
    id: 'emp-3',
    nombre: 'Ángel Ureña',
    cargo: 'Técnico de Control Técnico y Transmisión',
    tecnicoCode: 'AUreña',
    email: 'aurena@comunica.ec',
    saldoHoras: 16,
    codigoSeguridad: 'AU-2026',
    area: 'control_tecnico',
  },
  {
    id: 'emp-4',
    nombre: 'Patricio Cueva',
    cargo: 'Operador de Control Master y Satélite',
    tecnicoCode: 'PCueva',
    email: 'pcueva@comunica.ec',
    saldoHoras: 12,
    codigoSeguridad: 'PC-2026',
    area: 'control_tecnico',
  },
  {
    id: 'emp-5',
    nombre: 'Juan Espinoza',
    cargo: 'Técnico de Control Técnico Broadcast',
    tecnicoCode: 'JEspinoza',
    email: 'jespinoza@comunica.ec',
    saldoHoras: 8,
    codigoSeguridad: 'JE-2026',
    area: 'control_tecnico',
  },
  {
    id: 'emp-6',
    nombre: 'Fabricio López',
    cargo: 'Técnico de Transmisión y Frecuencias',
    tecnicoCode: 'FLopez',
    email: 'flopez@comunica.ec',
    saldoHoras: 4,
    codigoSeguridad: 'FL-2026',
    area: 'control_tecnico',
  },
];

export const INITIAL_CHECKLIST_ROWS: BroadcastChecklistRow[] = [
  {
    id: 'chk-1',
    programa: 'Noticiero Matinal',
    fecha: '2026-09-01',
    hora: '07h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'DQuevedo',
  },
  {
    id: 'chk-2',
    programa: 'Esto es ecuador',
    fecha: '2026-09-01',
    hora: '08h30',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'DQuevedo',
  },
  {
    id: 'chk-3',
    programa: 'Noticiero Central',
    fecha: '2026-09-01',
    hora: '12h30',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'DQuevedo',
  },
  {
    id: 'chk-4',
    programa: 'Doctor 7',
    fecha: '2026-09-01',
    hora: '17h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'Fmalla',
  },
  {
    id: 'chk-5',
    programa: 'Chef Bigotes',
    fecha: '2026-09-01',
    hora: '18h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'Fmalla',
  },
  {
    id: 'chk-6',
    programa: 'Noticiero Estelar',
    fecha: '2026-09-01',
    hora: '19h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'Fmalla',
  },
  {
    id: 'chk-7',
    programa: 'Deportes',
    fecha: '2026-09-01',
    hora: '21h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'Fmalla',
  },
  {
    id: 'chk-8',
    programa: 'Noticiero Matinal',
    fecha: '2026-09-02',
    hora: '07h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'DQuevedo',
  },
  {
    id: 'chk-9',
    programa: 'Esto es ecuador',
    fecha: '2026-09-02',
    hora: '08h30',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'DQuevedo',
  },
  {
    id: 'chk-10',
    programa: 'Noticiero Central',
    fecha: '2026-09-02',
    hora: '12h30',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'DQuevedo',
  },
  {
    id: 'chk-11',
    programa: 'Doctor 7',
    fecha: '2026-09-02',
    hora: '17h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'Fmalla',
  },
  {
    id: 'chk-12',
    programa: 'Chef Bigotes',
    fecha: '2026-09-02',
    hora: '18h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'Fmalla',
  },
  {
    id: 'chk-13',
    programa: 'Noticiero Estelar',
    fecha: '2026-09-02',
    hora: '19h00',
    enpsSvrPrimario: 'ok',
    enpsSvrSecundario: 'ok',
    noticiasK2Aire: 'ok',
    noticiasNexio: 'ok',
    legalrecRadio: 'ok',
    legalrecTv: 'ok',
    mosSvrPrincipal: 'ok',
    oradSrvHdvg: 'ok',
    oradMaestroPc: 'ok',
    provysSvrBdd: 'ok',
    prompterPcCliente: 'ok',
    zoomPcZoom: 'ok',
    internetEnlacePrincipal: 'ok',
    internetEnlaceSecundario: 'ok',
    observaciones: 'sin novedad',
    tecnicoTurno: 'Fmalla',
  }
];

export const INITIAL_INCIDENTS: IncidentTicket[] = [
  {
    id: 'inc-1',
    codigo: 'INC-2026-001',
    titulo: 'Pérdida de sincronización en servidor secundario ENPS',
    descripcion: 'Se detectó latencia en el espejo del servidor secundario previo al Noticiero Central. El primario sostuvo la emisión sin interrupción.',
    categoria: 'ENPS',
    prioridad: 'alta',
    estado: 'resuelto',
    tecnicoAsignado: 'DQuevedo',
    reportadoPor: 'Mesa de Producción',
    fechaReporte: '2026-09-01',
    horaReporte: '12:15',
    fechaSolucion: '2026-09-01 12:45',
    solucionAplicada: 'Reinicio de servicios de replicación MOS y reindexación de escaleta.'
  },
  {
    id: 'inc-2',
    codigo: 'INC-2026-002',
    titulo: 'Intermitencia de audio en enlace zoom estudio B',
    descripcion: 'Micro-cortes en entrada digital de PC-ZOOM durante prueba previa a transmisión con corresponsal de Guayaquil.',
    categoria: 'Zoom',
    prioridad: 'media',
    estado: 'en_progreso',
    tecnicoAsignado: 'Fmalla',
    reportadoPor: 'Control Técnico de Audio',
    fechaReporte: '2026-09-02',
    horaReporte: '16:20',
  },
  {
    id: 'inc-3',
    codigo: 'INC-2026-003',
    titulo: 'Enlace secundario de internet con pérdida de paquetes',
    descripcion: 'Fibra óptica redundante presenta jitter superior a 45ms. Se notifica al proveedor CNT.',
    categoria: 'Internet / Enlaces',
    prioridad: 'alta',
    estado: 'abierto',
    tecnicoAsignado: 'DQuevedo',
    reportadoPor: 'Monitoreo NOC',
    fechaReporte: '2026-09-02',
    horaReporte: '18:40',
  }
];

export const INITIAL_OVERTIME_LOGS: OvertimeLog[] = [
  {
    id: 'ot-2',
    empleadoId: 'emp-2',
    empleadoNombre: 'Freddy Malla',
    fecha: '2026-08-30',
    horasRealizadas: 8,
    recargo: '100%',
    horasEquivalentes: 16, // 8h * 2.0 = 16h (o según política de horas dobles en domingo)
    motivo: 'Transmisión en vivo dominical y soporte a elecciones seccionales',
    aprobadoPor: 'Gerencia de Operaciones',
    creadoEn: '2026-08-30 20:00',
  },
  {
    id: 'ot-3',
    empleadoId: 'emp-2',
    empleadoNombre: 'Freddy Malla',
    fecha: '2026-09-01',
    horasRealizadas: 3,
    recargo: '50%',
    horasEquivalentes: 4.5,
    motivo: 'Extensión de turno nocturno por contingencia en máster',
    aprobadoPor: 'Dirección Técnica',
    creadoEn: '2026-09-01 23:45',
  }
];

export const INITIAL_TIMEOFF_DEDUCTIONS: TimeOffDeduction[] = [
  {
    id: 'to-1',
    empleadoId: 'emp-2',
    empleadoNombre: 'Freddy Malla',
    fechaSolicitud: '2026-09-02',
    fechaDisfrute: '2026-09-05',
    tipo: 'horas',
    cantidadSolicitada: 4,
    horasDescontadas: 4,
    saldoPrevio: 28.0,
    saldoRestante: 24.0,
    motivo: 'Cita médica particular y trámites personales',
    estado: 'aprobado',
    creadoEn: '2026-09-02 10:00',
  }
];

// Initial rows based on official format CGCO-JO-2026-CHK-ING VERSIÓN: 01
export const INITIAL_CONTROL_TECNICO_ROWS: ControlTecnicoRow[] = [
  {
    id: 'ct-1',
    fecha: '2026-08-01',
    hora: '09:00',
    rxSatNacAv: true,
    rxSatNacCn: '13,91',
    rxSatNacLm: '7,1',
    rxSatNacBer: '0e-8',
    rxSatIntAv: true,
    rxSatIntCn: '14,9',
    rxSatIntLm: '7,18',
    rxSatIntBer: '0e-8',
    monAireAnalogaAu: true,
    monAireAnalogaVd: true,
    monAireHdAu: true,
    monAireHdVd: true,
    monAireSdAu: true,
    monAireSdVd: true,
    radioPubSatAu: true,
    radioPubInovonicAu: true,
    ctrlMasterNacAu: true,
    ctrlMasterNacVd: true,
    ctrlMasterIntAu: true,
    ctrlMasterIntVd: true,
    hispasatSrtAu: true,
    hispasatSrtVd: true,
    foPresPing: true,
    foGyePing: true,
    tempCer201: '20',
    tempCer202: 'N/A',
    observaciones: 'S/N',
    tecnicoTurno: 'AUreña',
  },
  {
    id: 'ct-2',
    fecha: '2026-08-01',
    hora: '10:44',
    rxSatNacAv: true,
    rxSatNacCn: '14,17',
    rxSatNacLm: '7,27',
    rxSatNacBer: '0e-8',
    rxSatIntAv: true,
    rxSatIntCn: '14,2',
    rxSatIntLm: '7,2',
    rxSatIntBer: '0e-8',
    monAireAnalogaAu: true,
    monAireAnalogaVd: true,
    monAireHdAu: true,
    monAireHdVd: true,
    monAireSdAu: true,
    monAireSdVd: true,
    radioPubSatAu: true,
    radioPubInovonicAu: true,
    ctrlMasterNacAu: true,
    ctrlMasterNacVd: true,
    ctrlMasterIntAu: true,
    ctrlMasterIntVd: true,
    hispasatSrtAu: true,
    hispasatSrtVd: true,
    foPresPing: true,
    foGyePing: true,
    tempCer201: '20',
    tempCer202: 'N/A',
    observaciones: 'S/N',
    tecnicoTurno: 'AUreña',
  },
  {
    id: 'ct-3',
    fecha: '2026-08-01',
    hora: '12:21',
    rxSatNacAv: true,
    rxSatNacCn: '14,09',
    rxSatNacLm: '7,18',
    rxSatNacBer: '0e-8',
    rxSatIntAv: true,
    rxSatIntCn: '14,27',
    rxSatIntLm: '7,17',
    rxSatIntBer: '0e-8',
    monAireAnalogaAu: true,
    monAireAnalogaVd: true,
    monAireHdAu: true,
    monAireHdVd: true,
    monAireSdAu: true,
    monAireSdVd: true,
    radioPubSatAu: true,
    radioPubInovonicAu: true,
    ctrlMasterNacAu: true,
    ctrlMasterNacVd: true,
    ctrlMasterIntAu: true,
    ctrlMasterIntVd: true,
    hispasatSrtAu: true,
    hispasatSrtVd: true,
    foPresPing: true,
    foGyePing: true,
    tempCer201: '20',
    tempCer202: 'N/A',
    observaciones: 'S/N',
    tecnicoTurno: 'AUreña',
  },
  {
    id: 'ct-4',
    fecha: '2026-08-02',
    hora: '10:31',
    rxSatNacAv: true,
    rxSatNacCn: '14,01',
    rxSatNacLm: '7,1',
    rxSatNacBer: '0e-8',
    rxSatIntAv: true,
    rxSatIntCn: '14,1',
    rxSatIntLm: '7,2',
    rxSatIntBer: '0e-8',
    monAireAnalogaAu: true,
    monAireAnalogaVd: true,
    monAireHdAu: true,
    monAireHdVd: true,
    monAireSdAu: true,
    monAireSdVd: true,
    radioPubSatAu: true,
    radioPubInovonicAu: true,
    ctrlMasterNacAu: true,
    ctrlMasterNacVd: true,
    ctrlMasterIntAu: true,
    ctrlMasterIntVd: true,
    hispasatSrtAu: true,
    hispasatSrtVd: true,
    foPresPing: true,
    foGyePing: true,
    tempCer201: '20',
    tempCer202: 'N/A',
    observaciones: 'S/N',
    tecnicoTurno: 'PCueva',
  },
  {
    id: 'ct-5',
    fecha: '2026-08-03',
    hora: '15:30',
    rxSatNacAv: true,
    rxSatNacCn: '14,14',
    rxSatNacLm: '7,19',
    rxSatNacBer: '0e-8',
    rxSatIntAv: true,
    rxSatIntCn: '14,23',
    rxSatIntLm: '7,32',
    rxSatIntBer: '0e-8',
    monAireAnalogaAu: true,
    monAireAnalogaVd: true,
    monAireHdAu: true,
    monAireHdVd: true,
    monAireSdAu: true,
    monAireSdVd: true,
    radioPubSatAu: true,
    radioPubInovonicAu: true,
    ctrlMasterNacAu: true,
    ctrlMasterNacVd: true,
    ctrlMasterIntAu: true,
    ctrlMasterIntVd: true,
    hispasatSrtAu: true,
    hispasatSrtVd: true,
    foPresPing: true,
    foGyePing: true,
    tempCer201: '20',
    tempCer202: 'N/A',
    observaciones: 'S/N',
    tecnicoTurno: 'JEspinoza',
  },
  {
    id: 'ct-6',
    fecha: '2026-08-03',
    hora: '16:29',
    rxSatNacAv: true,
    rxSatNacCn: '14,21',
    rxSatNacLm: '7,31',
    rxSatNacBer: '0e-8',
    rxSatIntAv: true,
    rxSatIntCn: '13,89',
    rxSatIntLm: '6,98',
    rxSatIntBer: '0e-8',
    monAireAnalogaAu: true,
    monAireAnalogaVd: true,
    monAireHdAu: true,
    monAireHdVd: true,
    monAireSdAu: true,
    monAireSdVd: true,
    radioPubSatAu: true,
    radioPubInovonicAu: true,
    ctrlMasterNacAu: true,
    ctrlMasterNacVd: true,
    ctrlMasterIntAu: true,
    ctrlMasterIntVd: true,
    hispasatSrtAu: true,
    hispasatSrtVd: true,
    foPresPing: true,
    foGyePing: true,
    tempCer201: '20',
    tempCer202: 'N/A',
    observaciones: 'S/N',
    tecnicoTurno: 'FLopez',
  },
];

// Initial IPv4 Networks
export const INITIAL_IPV4_NETWORKS: Ipv4Network[] = [
  {
    id: 'net-1',
    nombre: 'Red Broadcast Playout & Servidores CER',
    segmento: '192.168.10.0/24',
    vlan: 'VLAN 10',
    gateway: '192.168.10.1',
    mascara: '255.255.255.0',
    dnsPrimario: '192.168.10.2',
    ubicacion: 'Rack Central CER - Piso 2',
    descripcion: 'Segmento crítico para playout K2, Nexio, servidores ENPS y bases de datos Provys.',
    creadoEn: '2026-08-01',
  },
  {
    id: 'net-2',
    nombre: 'Red Controles Master & Estudios TV',
    segmento: '192.168.20.0/24',
    vlan: 'VLAN 20',
    gateway: '192.168.20.1',
    mascara: '255.255.255.0',
    dnsPrimario: '192.168.10.2',
    ubicacion: 'Control Master TV & Cabinas de Audio',
    descripcion: 'Equipos de emisión, prompters, estaciones de titulación Orad y consolas master.',
    creadoEn: '2026-08-01',
  },
  {
    id: 'net-3',
    nombre: 'Red Transmisión Satelital & Enlaces F.O.',
    segmento: '10.50.100.0/24',
    vlan: 'VLAN 100',
    gateway: '10.50.100.1',
    mascara: '255.255.255.0',
    dnsPrimario: '8.8.8.8',
    ubicacion: 'Sala de Transmisores & Telepuerto',
    descripcion: 'Receptores satelitales, encoders SRT Hispasat, enlaces F.O. Presidencia y Guayaquil.',
    creadoEn: '2026-08-01',
  },
];

// Initial IPv4 Assignments
export const INITIAL_IP_ASSIGNMENTS: IpAssignment[] = [
  {
    id: 'ip-1',
    networkId: 'net-1',
    ip: '192.168.10.10',
    hostname: 'SRV-ENPS-PRIMARIO',
    tipoDispositivo: 'servidor',
    macAddress: '00:15:5D:01:10:A1',
    ubicacion: 'Rack CER 01 - U12',
    estado: 'asignada',
    responsable: 'Darwin Quevedo',
    observaciones: 'Servidor AP ENPS de redacción principal',
    ultimaModificacion: '2026-08-01',
  },
  {
    id: 'ip-2',
    networkId: 'net-1',
    ip: '192.168.10.11',
    hostname: 'SRV-ENPS-SECUNDARIO',
    tipoDispositivo: 'servidor',
    macAddress: '00:15:5D:01:10:A2',
    ubicacion: 'Rack CER 01 - U14',
    estado: 'asignada',
    responsable: 'Darwin Quevedo',
    observaciones: 'Servidor réplica y contingencia ENPS',
    ultimaModificacion: '2026-08-01',
  },
  {
    id: 'ip-3',
    networkId: 'net-1',
    ip: '192.168.10.15',
    hostname: 'K2-SERVER-AIRE',
    tipoDispositivo: 'servidor',
    macAddress: '70:B5:E8:4A:22:90',
    ubicacion: 'Rack CER 02 - U08',
    estado: 'asignada',
    responsable: 'Freddy Malla',
    observaciones: 'Servidor Grass Valley K2 canal aire',
    ultimaModificacion: '2026-08-01',
  },
  {
    id: 'ip-4',
    networkId: 'net-1',
    ip: '192.168.10.16',
    hostname: 'NEXIO-NEWS-SAN',
    tipoDispositivo: 'servidor',
    macAddress: '70:B5:E8:4A:33:14',
    ubicacion: 'Rack CER 02 - U10',
    estado: 'asignada',
    responsable: 'Freddy Malla',
    observaciones: 'Almacenamiento compartido noticias Nexio',
    ultimaModificacion: '2026-08-01',
  },
  {
    id: 'ip-5',
    networkId: 'net-1',
    ip: '192.168.10.20',
    hostname: 'ORAD-HDVG-RENDER',
    tipoDispositivo: 'servidor',
    macAddress: '3C:D9:2B:6F:88:02',
    ubicacion: 'Rack CER 03 - U15',
    estado: 'asignada',
    responsable: 'Darwin Quevedo',
    observaciones: 'Motor gráfico en tiempo real HDVG+',
    ultimaModificacion: '2026-08-01',
  },
  {
    id: 'ip-6',
    networkId: 'net-2',
    ip: '192.168.20.25',
    hostname: 'PC-PROMPTER-ESTUDIO-A',
    tipoDispositivo: 'prompter',
    macAddress: 'E4:54:E8:11:45:90',
    ubicacion: 'Estudio Central A',
    estado: 'asignada',
    responsable: 'Freddy Malla',
    observaciones: 'Cliente de teleprompter en set',
    ultimaModificacion: '2026-08-01',
  },
  {
    id: 'ip-7',
    networkId: 'net-2',
    ip: '192.168.20.30',
    hostname: 'PC-ZOOM-RECEPCION',
    tipoDispositivo: 'estacion_trabajo',
    macAddress: 'E4:54:E8:22:98:71',
    ubicacion: 'Cabina Híbrida Noticias',
    estado: 'asignada',
    responsable: 'Darwin Quevedo',
    observaciones: 'Ingesta de entrevistas remotas Zoom/Teams',
    ultimaModificacion: '2026-08-01',
  },
  {
    id: 'ip-8',
    networkId: 'net-3',
    ip: '10.50.100.2',
    hostname: 'TX-HISPASAT-SRT-PRI',
    tipoDispositivo: 'encoder_decoder',
    macAddress: '00:0B:82:91:AA:50',
    ubicacion: 'Sala Transmisores - Rack TX1',
    estado: 'asignada',
    responsable: 'Ángel Ureña',
    observaciones: 'Encoder SRT subida satelital Hispasat',
    ultimaModificacion: '2026-08-01',
  },
  {
    id: 'ip-9',
    networkId: 'net-3',
    ip: '10.50.100.5',
    hostname: 'SW-CORE-FO-PRESIDENCIA',
    tipoDispositivo: 'switch_router',
    macAddress: '00:24:14:FE:80:01',
    ubicacion: 'Rack Fibra Óptica',
    estado: 'asignada',
    responsable: 'Patricio Cueva',
    observaciones: 'Switch de interconexión anillo óptico Presidencia',
    ultimaModificacion: '2026-08-01',
  },
];
